name: diabetic-retinopathy-screening
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.*
  - torchvision
  - timm
  - opencv
  - scikit-learn
  - pandas
  - matplotlib
  - tqdm
  - kaggle
  - unzip
